version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:3.4.4
    steps:
      - run: npm install
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test