version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
        port: 3000:3000
    steps:
      - checkout
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test
